### PR TITLE
Add Tooltip Scroll and an issue template

### PR DESCRIPTION
**Pull request by stantios**
Description: This PR adds the mod [Tooltip Scroll](https://modrinth.com/mod/tooltip-scroll) and a config for the mod as suggested on Discord.

This PR also adds an issue template for requesting and suggesting mods. For a preview of the template, look here: <https://github.com/Imzxhir/unofficial-quilt-smp-the-3rd/issues/new/choose>

### CODE REVIEW

**Comment by Abbie5** [comment]
shouldnt this pr also remove tooltipfix as they solve the same problem?

**Comment by stantios** [comment]
Well, Tooltipfix fixes tooltips and Tooltip Scroll makes tooltips scrollable. I am not sure if I should remove Tooltip Fix, I did hear about an issue where they weren't working with EMI.

**Comment by Abbie5** [comment]
i see, may i suggest making tooltipfix optional then? there doesn't seem to be a way to configure it

**Comment by woodiertexas** [comment]
To be fair, i think tooltip scroll fixes the "very large tooltip" issue.

**Pull request merged**
