### PR TITLE
add more mods, redo configs, remove some mods

### PR DESCRIPTION
**Pull request by woodiertexas**

### CODE REVIEW

**Comment by stantios** [comment]
This PR includes these mods from the GitHub Issue Tracker: https://github.com/woodiertexas/unofficial-quilt-smp-the-3rd/issues/17 https://github.com/woodiertexas/unofficial-quilt-smp-the-3rd/issues/20 https://github.com/woodiertexas/unofficial-quilt-smp-the-3rd/issues/19 https://github.com/woodiertexas/unofficial-quilt-smp-the-3rd/issues/9

**Review by stantios — APPROVED** [review]
Looks great to me. Should we add [Cinderscape](https://modrinth.com/mod/cinderscapes) since we are replacing Incendium?

**Comment by woodiertexas** [comment]
> Looks great to me. Should we add [Cinderscape](https://modrinth.com/mod/cinderscapes) since we are replacing Incendium?

it's in the pack: https://github.com/woodiertexas/unofficial-quilt-smp-the-3rd/blob/main/mods/cinderscapes.pw.toml

**Comment by woodiertexas** [comment]
also, latest commit closes: https://github.com/woodiertexas/unofficial-quilt-smp-the-3rd/issues/33, https://github.com/woodiertexas/unofficial-quilt-smp-the-3rd/issues/24, https://github.com/woodiertexas/unofficial-quilt-smp-the-3rd/issues/20, https://github.com/woodiertexas/unofficial-quilt-smp-the-3rd/issues/19, https://github.com/woodiertexas/unofficial-quilt-smp-the-3rd/issues/17, https://github.com/woodiertexas/unofficial-quilt-smp-the-3rd/issues/13, and https://github.com/woodiertexas/unofficial-quilt-smp-the-3rd/issues/9

**Comment by stantios** [comment]
> > Looks great to me. Should we add [Cinderscape](https://modrinth.com/mod/cinderscapes) since we are replacing Incendium?
> 
> it's in the pack: [`main`/mods/cinderscapes.pw.toml](https://github.com/woodiertexas/unofficial-quilt-smp-the-3rd/blob/main/mods/cinderscapes.pw.toml?rgh-link-date=2023-09-19T10%3A15%3A38Z)

Oh, I see. That’s nice

**Pull request merged**
